theme = "ayu_dark"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
auto-save = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
